#!/usr/bin/env python3
from http.server import BaseHTTPRequestHandler
from socketserver import TCPServer
from urllib.parse import unquote
import argparse
import json
import re
import shlex
import subprocess
import tempfile
import webbrowser

parser = argparse.ArgumentParser()
parser.add_argument('profile', type=argparse.FileType('r'), metavar='profile.ovpn')
args = parser.parse_args()


def get_url():
    regex = re.compile('^#AviatrixController (.*)$')
    for line in args.profile.readlines():
        match = regex.match(line)
        if match:
            return match.group(1)
    raise RuntimeError("Controller URL not found in profile")


def openvpn(username, password):
    cmd = 'sudo openvpn --config {config} --auth-user-pass {userpass}'
    with tempfile.NamedTemporaryFile() as passfile:
        passfile.write((username + '\n').encode())
        passfile.write((password + '\n').encode())
        passfile.flush()
        cmd = cmd.format(userpass=passfile.name, config=args.profile.name)
        proc = subprocess.Popen(shlex.split(cmd))
        proc.communicate()


class Handler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        return

    def do_POST(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        self.wfile.write(b'SuccessAviatrix')
        credentials = json.loads(unquote(self.path[1:]))
        openvpn(credentials['Email'], credentials['Token'])


TCPServer.allow_reuse_address = True
with TCPServer(('localhost', 15395), Handler) as httpd:
    webbrowser.open(get_url())
    httpd.handle_request()
