#!/usr/bin/env python3
from http.server import BaseHTTPRequestHandler
from socketserver import TCPServer
from urllib.parse import unquote
import argparse
import json
import re
import shlex
import subprocess
import tempfile
import webbrowser

parser = argparse.ArgumentParser()
parser.add_argument('profile', type=argparse.FileType('r'), metavar='profile.ovpn')
args = parser.parse_args()


def get_url():
    regex = re.compile('^#AviatrixController (.*)$')
    for line in args.profile.readlines():
        match = regex.match(line)
        if match:
            return match.group(1)
    raise RuntimeError("Controller URL not found in profile")


def openvpn(username, password):
    with tempfile.NamedTemporaryFile(mode='w+', buffering=1) as passfile:
        passfile.write(f'{username}\n')
        passfile.write(f'{password}\n')
        cmd = f'sudo openvpn --config {args.profile.name} --auth-user-pass {passfile.name}'
        subprocess.run(shlex.split(cmd))


class Handler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        return

    def do_POST(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        self.wfile.write(b'SuccessAviatrix')
        global credentials
        credentials = json.loads(unquote(self.path[1:]))


TCPServer.allow_reuse_address = True
with TCPServer(('localhost', 15395), Handler) as httpd:
    webbrowser.open(get_url())
    httpd.handle_request()

openvpn(credentials['Email'], credentials['Token'])
